[[plugins]]
repo  = 'w0rp/ale'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = 'noremap <C-X><C-T> :VimFiler -split -simple -winwidth=45 -no-quit<ENTER>'
hook_source = 'let g:vimfiler_as_default_explorer = 1'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'StanAngeloff/php.vim'

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'google/vim-jsonnet'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'cstrahan/vim-capnp'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'williamboman/mason.nvim'
